import { PageHero } from "@/components/layout/PageHero";
import { SectionSeparator } from "@/components/ui/SectionSeparator";
import { CTAButton } from "@/components/ui/CTAButton";
import { SeeAlso } from "@/components/ui/SeeAlso";
import { Reveal } from "@/components/motion/Reveal";
import Link from "next/link";

const captureCards = [
  {
    title: "Monitored competitors",
    description: "Prioritized URLs and domains with tag maps showing which offers gained visibility.",
  },
  {
    title: "Detected patterns",
    description: "Copy changes, new prices, bundles, testimonials, and positioning shifts in ads.",
  },
  {
    title: "Relevant changes",
    description: "Alerts on new players, announced partnerships, and tone-of-voice shifts.",
  },
];

export default function ScoutModulePage() {
  return (
    <div className="bg-white">
      <PageHero
        breadcrumbs={[
          { label: "Home", href: "/" },
          { label: "Modules", href: "/modules" },
          { label: "Scout" },
        ]}
        subtitle="Intelligence module"
        title="Scout: the observer that reads competitors and trends in human language."
        body="Scout monitors pages, ads, social media, marketplaces, and competitor announcements. For every variation it detects, it creates a readable summary, flags relevant changes, and estimates impact. The module learns your team and sector preferences, surfacing only what matters. Integrated into biweekly rituals, it cuts manual research time and feeds the marketing, product, and sales backlogs."
        ctas={[
          {
            label: "See sample summary",
            href: "/projects?utm_source=module-scout&utm_campaign=cta-primary",
            ariaLabel: "See summary generated by Scout",
            campaign: "cta-primary",
          },
          {
            label: "Connect with automation",
            href: "/services/automation?utm_source=module-scout&utm_campaign=cta-secondary",
            ariaLabel: "Connect Scout with automations",
            variant: "secondary",
            campaign: "cta-secondary",
          },
        ]}
        source="module-scout-hero"
      />

      <SectionSeparator />

      <section className="px-4 py-24">
        <div className="mx-auto max-w-screen-xl space-y-12 lg:px-8">
          <div className="rounded-[var(--radius-card)] border border-line bg-surface p-8 shadow-[var(--shadow-soft)]">
            <h2 className="text-2xl font-semibold text-ink">What Scout captures</h2>
            <div className="mt-6 grid gap-6 md:grid-cols-3">
              {captureCards.map((card, idx) => (
                <Reveal key={card.title} variant="fadeInUp" delay={60 * idx}>
                  <div className="h-full rounded-[var(--radius-card)] border border-line bg-white p-6 text-sm text-muted shadow-[var(--shadow-soft)] transition hover:-translate-y-1 hover:shadow-[var(--shadow-elevated)]">
                    <h3 className="text-lg font-semibold text-ink">{card.title}</h3>
                    <p className="mt-3">{card.description}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>

          <div className="grid gap-8 md:grid-cols-[1.2fr_0.8fr]">
            <div className="rounded-[var(--radius-card)] border border-line bg-white p-8 shadow-[var(--shadow-soft)]">
              <h2 className="text-2xl font-semibold text-ink">Practical uses</h2>
              <ul className="mt-4 space-y-2 text-sm text-muted">
                <li className="flex items-start gap-2">
                  <span className="mt-1 inline-flex h-2 w-2 rounded-full bg-brand" />
                  <span>
                    Weekly briefings for{" "}
                    <Link
                      href="/services/marketing?utm_source=module-scout-body&utm_campaign=link"
                      className="text-brand underline-offset-4 transition hover:text-brand-600 hover:underline"
                    >
                      marketing
                    </Link>{" "}
                    squads with context and suggested actions.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1 inline-flex h-2 w-2 rounded-full bg-brand" />
                  <span>
                    Updates to{" "}
                    <Link
                      href="/services/websites?utm_source=module-scout-body&utm_campaign=link"
                      className="text-brand underline-offset-4 transition hover:text-brand-600 hover:underline"
                    >
                      website
                    </Link>{" "}
                    flows and landing pages when competitors change narrative.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1 inline-flex h-2 w-2 rounded-full bg-brand" />
                  <span>
                    Inputs for{" "}
                    <Link
                      href="/services/automation?utm_source=module-scout-body&utm_campaign=link"
                      className="text-brand underline-offset-4 transition hover:text-brand-600 hover:underline"
                    >
                      nurture automations
                    </Link>{" "}
                    and follow-up.
                  </span>
                </li>
              </ul>
              <CTAButton
                href="/modules/insightscore?utm_source=module-scout&utm_campaign=cta-ghost"
                label="Send insights to InsightScore™"
                ariaLabel="Send Scout insights to InsightScore"
                variant="ghost"
                source="module-scout-body"
                campaign="cta-ghost"
                className="mt-6"
              />
            </div>
            <div className="rounded-[var(--radius-card)] border border-line bg-surface p-8 shadow-[var(--shadow-soft)] text-sm text-muted">
              <h2 className="text-2xl font-semibold text-ink">Recommended rituals</h2>
              <p className="mt-3">
                • Monday: quick read (15 min) of alerts. • Wednesday: tactical meeting with prioritized insights. •
                Friday: backlog update with approved actions.
              </p>
              <p className="mt-4">
                Everything is logged in the dashboard with history, attachments, and custom fields for internal squads.
              </p>
            </div>
          </div>
        </div>
      </section>

      <SeeAlso
        source="module-scout-see-also"
        items={[
          {
            title: "AQUA Insights",
            description: "Connect market language with signals from Scout.",
            href: "/modules/aqua",
          },
          {
            title: "InsightScore™",
            description: "Turn observations into prioritized actions.",
            href: "/modules/insightscore",
          },
          {
            title: "Intelligent marketing",
            description: "See how squads use Scout day to day.",
            href: "/services/marketing",
          },
          {
            title: "Dashboard /app",
            description: "Monitor KPIs and insight history in one place.",
            href: "/app",
          },
        ]}
      />
    </div>
  );
}
